name: Generate lockfile

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-audit --fund=false

      - name: Verify lockfile existence
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found"
            exit 1
          fi

      - name: Open pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci/add-lockfile
          title: "chore: add package-lock.json"
          commit-message: "chore: add package-lock.json"
          add-paths: |
            package-lock.json
          body: |
            ## Summary
            - Add the generated package-lock.json file.
            
            ## Testing
            - npm install --no-audit --fund=false
